(function(){
var STORAGE_KEY='misha_data_v3';
var state={settings:{groq:'',elevenLabs:'',gemini:'',googleClientId:'',voiceURI:''},googleToken:null,googleEvents:[],profile:null,flashcards:[],events:[],tasks:[],stats:{pomodoros:0,focusMinutes:0,streak:0},chatHistory:[],currentFC:0,pomodoro:{running:false,seconds:1500,total:1500,interval:null},micActive:false,recognition:null,isSpeaking:false};
var SYSTEM_PROMPT='Voce e o MISHA, amigo e tutor de estudos. Fale como pessoa real em portugues do Brasil: natural, curto, tom de conversa. Respostas curtas (2 a 5 frases). Sem markdown. Pode perguntar de volta. Explica simples. Nunca diga que e um modelo.';
var tokenClient=null;
function $(id){return document.getElementById(id);}
function loadState(){try{var raw=localStorage.getItem(STORAGE_KEY);if(raw){var s=JSON.parse(raw);if(s.settings)Object.assign(state.settings,s.settings);if(s.profile)state.profile=s.profile;if(s.flashcards)state.flashcards=s.flashcards;if(s.events)state.events=s.events;if(s.tasks)state.tasks=s.tasks;if(s.stats)Object.assign(state.stats,s.stats);}['misha_data_v2','misha_data_v1'].forEach(function(k){var old=localStorage.getItem(k);if(!old)return;try{var o=JSON.parse(old);if(o.settings){if(!state.settings.groq&&o.settings.groq)state.settings.groq=o.settings.groq;if(!state.settings.gemini&&o.settings.gemini)state.settings.gemini=o.settings.gemini;if(!state.settings.elevenLabs&&o.settings.elevenLabs)state.settings.elevenLabs=o.settings.elevenLabs;if(!state.settings.googleClientId&&o.settings.googleClientId)state.settings.googleClientId=o.settings.googleClientId;}if(!state.profile&&o.profile)state.profile=o.profile;if(!state.flashcards.length&&o.flashcards)state.flashcards=o.flashcards;if(!state.events.length&&o.events)state.events=o.events;if(!state.tasks.length&&o.tasks)state.tasks=o.tasks;}catch(e){}});}catch(e){}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({settings:state.settings,profile:state.profile,flashcards:state.flashcards,events:state.events,tasks:state.tasks,stats:state.stats}));updateStatsUI();}
function toast(msg,d){d=d||3000;var el=$('toast');el.textContent=msg;el.style.display='block';setTimeout(function(){el.style.display='none';},d);}
function addChat(role,text){var log=$('chatLog');var div=document.createElement('div');div.className='chat-msg'+(role==='user'?' text-right':'');div.innerHTML='<span class="'+(role==='user'?'text-cyan-300':'text-purple-300')+' font-semibold">'+(role==='user'?'Voce':'MISHA')+':</span> <span class="text-cyan-200">'+text+'</span>';log.appendChild(div);log.scrollTop=log.scrollHeight;}
function setOrbState(s){var orb=$('orb');orb.classList.remove('listening','thinking','speaking');if(s)orb.classList.add(s);$('orbStatus').textContent=({listening:'Ouvindo...',thinking:'Pensando...',speaking:'Falando...','':'Aguardando'})[s]||'Aguardando';}
function updateStatsUI(){$('statPomodoros').textContent=state.stats.pomodoros;$('statFlashcards').textContent=state.flashcards.length;$('statStreak').textContent=state.stats.streak+'d';$('statFocus').textContent=state.stats.focusMinutes+'m';}
function updateClock(){$('clockDisplay').textContent=new Date().toLocaleString('pt-BR',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});}
function openSettings(){$('cfgGroq').value=state.settings.groq||'';$('cfgEleven').value=state.settings.elevenLabs||'';$('cfgGemini').value=state.settings.gemini||'';var gc=$('cfgGoogleClient');if(gc)gc.value=state.settings.googleClientId||'';populateVoices();$('settingsModal').style.display='flex';}
function closeSettings(){$('settingsModal').style.display='none';}
function saveSettings(){state.settings.groq=$('cfgGroq').value.trim();state.settings.elevenLabs=$('cfgEleven').value.trim();state.settings.gemini=$('cfgGemini').value.trim();var gc=$('cfgGoogleClient');if(gc)state.settings.googleClientId=gc.value.trim();state.settings.voiceURI=$('cfgVoice').value;saveState();closeSettings();toast('Salvo!');}
function populateVoices(){var sel=$('cfgVoice');sel.innerHTML='';speechSynthesis.getVoices().forEach(function(v){var o=document.createElement('option');o.value=v.voiceURI;o.textContent=v.name+' ('+v.lang+')';if(v.voiceURI===state.settings.voiceURI)o.selected=true;sel.appendChild(o);});}
speechSynthesis.onvoiceschanged=populateVoices;
function stopSpeaking(){try{speechSynthesis.cancel();}catch(e){}state.isSpeaking=false;}
function resumeMic(){if(state.micActive&&state.recognition)setTimeout(function(){try{state.recognition.start();}catch(e){}},400);}
function fallbackSpeak(text){stopSpeaking();state.isSpeaking=true;setOrbState('speaking');var u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=1.02;var voices=speechSynthesis.getVoices();var p=null;for(var i=0;i<voices.length;i++){if(voices[i].voiceURI===state.settings.voiceURI){p=voices[i];break;}}if(!p){for(var j=0;j<voices.length;j++){if(voices[j].lang.indexOf('pt')===0){p=voices[j];break;}}}if(p)u.voice=p;u.onend=u.onerror=function(){state.isSpeaking=false;setOrbState(state.micActive?'listening':'');resumeMic();};speechSynthesis.speak(u);}
async function mishaSpeak(text){if(!text)return;stopSpeaking();addChat('misha',text);setOrbState('speaking');state.isSpeaking=true;if(state.recognition&&state.micActive)try{state.recognition.stop();}catch(e){}if(state.settings.elevenLabs){try{var res=await fetch('https://api.elevenlabs.io/v1/text-to-speech/pNInz6obpgDQGcFmaJgB',{method:'POST',headers:{'Accept':'audio/mpeg','Content-Type':'application/json','xi-api-key':state.settings.elevenLabs},body:JSON.stringify({text:text,model_id:'eleven_multilingual_v2',voice_settings:{stability:0.5,similarity_boost:0.75}})});if(res.ok){var url=URL.createObjectURL(await res.blob());var audio=new Audio(url);audio.onended=function(){state.isSpeaking=false;setOrbState(state.micActive?'listening':'');URL.revokeObjectURL(url);resumeMic();};audio.onerror=function(){fallbackSpeak(text);};await audio.play();return;}}catch(e){}}fallbackSpeak(text);}
function initRecognition(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Use o Chrome');return null;}var rec=new SR();rec.continuous=true;rec.interimResults=true;rec.lang='pt-BR';rec.onresult=function(e){if(state.isSpeaking)return;var interim='',finalText='';for(var i=e.resultIndex;i<e.results.length;i++){var t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=t;else interim+=t;}var lh=$('lastHeard');if(finalText)lh.textContent='Ouvi: "'+finalText.trim()+'"';else if(interim)lh.textContent='Ouvindo: "'+interim.trim()+'..."';if(finalText.trim())handleVoiceInput(finalText.trim());};rec.onerror=function(e){if(e.error==='not-allowed'){toast('Mic bloqueado');stopMic();}};rec.onend=function(){if(state.micActive&&!state.isSpeaking)try{rec.start();}catch(e){}};return rec;}
function startMic(){if(!state.recognition)state.recognition=initRecognition();if(!state.recognition)return;try{state.recognition.start();state.micActive=true;$('micIcon').textContent='\uD83D\uDD34';$('micBtnText').textContent='PARAR';$('btnVoiceMode').classList.add('active');$('micStatus').className='status-dot online';$('micStatusText').textContent='Ouvindo';setOrbState('listening');toast('Pode falar!');}catch(e){toast('Erro no mic');}}
function stopMic(){state.micActive=false;if(state.recognition)try{state.recognition.stop();}catch(e){}$('micIcon').textContent='\uD83C\uDF99';$('micBtnText').textContent='FALAR COM O MISHA';$('btnVoiceMode').classList.remove('active');$('micStatus').className='status-dot offline';$('micStatusText').textContent='Mic offline';setOrbState('');$('lastHeard').textContent='';}
function toggleMic(){state.micActive?stopMic():startMic();}
function handleVoiceInput(transcript){if(!transcript||state.isSpeaking)return;$('lastHeard').textContent='Ouvi: "'+transcript+'"';var cmd=transcript.replace(/\b(misha|micha|mixa|misa|mecha)\b/gi,'').trim();if(!cmd||cmd.length<2)return;addChat('user',transcript);processCommand(cmd);}
function sendTextCmd(){var input=$('textCmd');var text=(input.value||'').trim();if(!text)return;input.value='';addChat('user',text);processCommand(text);}
function initGoogleAuth(){if(typeof google==='undefined'||!google.accounts){toast('Google ainda carregando, tente de novo');return false;}if(!state.settings.googleClientId){toast('Cole o Google Client ID nas configuracoes');return false;}tokenClient=google.accounts.oauth2.initTokenClient({client_id:state.settings.googleClientId,scope:'https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.readonly',callback:function(resp){if(resp&&resp.access_token){state.googleToken=resp.access_token;var gs=$('googleStatus');if(gs)gs.textContent='Conectado';toast('Google Agenda conectada!');loadGoogleCalendar();}else toast('Falha ao conectar Google');}});return true;}
function connectGoogle(){if(!state.settings.googleClientId){openSettings();toast('Cole o Client ID, salve, e clique em Conectar');return;}if(!initGoogleAuth())return;tokenClient.requestAccessToken({prompt:'consent'});}
async function loadGoogleCalendar(){if(!state.googleToken){toast('Conecte o Google Agenda primeiro');return;}try{var timeMin=new Date();timeMin.setDate(timeMin.getDate()-7);var timeMax=new Date();timeMax.setDate(timeMax.getDate()+60);var url='https://www.googleapis.com/calendar/v3/calendars/primary/events?maxResults=30&orderBy=startTime&singleEvents=true&timeMin='+encodeURIComponent(timeMin.toISOString())+'&timeMax='+encodeURIComponent(timeMax.toISOString());var res=await fetch(url,{headers:{'Authorization':'Bearer '+state.googleToken}});var data=await res.json();if(data.error){toast('Erro Calendar: '+(data.error.message||''));return;}state.googleEvents=(data.items||[]).map(function(ev){var start=(ev.start&&(ev.start.dateTime||ev.start.date))||'';return {id:ev.id,title:ev.summary||'(sem titulo)',date:start.slice(0,10),type:'google'};});renderSchedule();toast(state.googleEvents.length+' eventos do Google');}catch(e){console.warn(e);toast('Erro ao ler Calendar');}}
async function createGoogleEvent(title,date){if(!state.googleToken)return null;try{var res=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{'Authorization':'Bearer '+state.googleToken,'Content-Type':'application/json'},body:JSON.stringify({summary:title,start:{date:date},end:{date:date}})});var data=await res.json();if(data.error){toast('Erro ao criar: '+(data.error.message||''));return null;}toast('Evento criado no Google!');await loadGoogleCalendar();return data;}catch(e){toast('Erro ao criar evento');return null;}}
async function askAI(userMsg,extra){state.chatHistory.push({role:'user',content:userMsg});if(state.chatHistory.length>14)state.chatHistory=state.chatHistory.slice(-14);var sys=SYSTEM_PROMPT+(extra?' '+extra:'');if(state.profile)sys+=' Estudante: '+(state.profile.name||'')+'. Estuda: '+(state.profile.occupation||'')+'. Meta: '+(state.profile.goal||'')+'.';if(state.settings.groq){try{var messages=[{role:'system',content:sys}].concat(state.chatHistory);var models=['openai/gpt-oss-20b','openai/gpt-oss-120b','qwen/qwen3.8-27b','qwen/qwen3.6-27b'];var lastErr='';for(var gi=0;gi<models.length;gi++){var res=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.groq},body:JSON.stringify({model:models[gi],messages:messages,temperature:0.85,max_tokens:400})});var data=await res.json();if(data&&data.error){lastErr=data.error.message||'';continue;}if(data&&data.choices&&data.choices[0]&&data.choices[0].message){var reply=(data.choices[0].message.content||'').trim();if(reply){state.chatHistory.push({role:'assistant',content:reply});return reply;}}}if(lastErr)toast('Erro Groq: '+lastErr,4000);}catch(e){console.warn(e);}}if(state.settings.gemini){try{var gModels=['gemini-2.5-flash','gemini-2.5-flash-lite','gemini-flash-latest'];var hist=state.chatHistory.slice(-6).map(function(m){return(m.role==='user'?'Usuario: ':'MISHA: ')+m.content;}).join('\n');var prompt=sys+'\n\n'+hist+'\n\nResponda em tom de conversa.';for(var mi=0;mi<gModels.length;mi++){var gRes=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+gModels[mi]+':generateContent?key='+encodeURIComponent(state.settings.gemini),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.85,maxOutputTokens:400}})});var gData=await gRes.json();if(gData&&gData.error)continue;var gReply=gData&&gData.candidates&&gData.candidates[0]&&gData.candidates[0].content&&gData.candidates[0].content.parts&&gData.candidates[0].content.parts[0]&&gData.candidates[0].content.parts[0].text;if(gReply){gReply=gReply.trim();state.chatHistory.push({role:'assistant',content:gReply});return gReply;}}}catch(e){}}return null;}
async function processCommand(cmd){setOrbState('thinking');var lower=cmd.toLowerCase();if(/pomodoro|timer|foco/.test(lower)){if(/parar|pausar/.test(lower)){pausePomodoro();mishaSpeak('Pomodoro pausado.');return;}startPomodoro();mishaSpeak('Pomodoro iniciado!');return;}if(/flashcard|cartao/.test(lower)){if(state.flashcards.length){showFlashcard();mishaSpeak('Flashcard: '+state.flashcards[state.currentFC].front);}else mishaSpeak('Sem flashcards ainda.');return;}if(/que horas|horario/.test(lower)){mishaSpeak('Agora sao '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+'.');return;}var reply=await askAI(cmd);if(reply)mishaSpeak(reply);else mishaSpeak('Coloca a chave Groq em Configuracoes.');}
function showFlashcardForm(){$('flashcardForm').classList.remove('hidden');}
function saveFlashcard(){var f=$('fcFrontInput').value.trim(),b=$('fcBackInput').value.trim();if(!f||!b){toast('Preencha os campos');return;}state.flashcards.push({front:f,back:b});saveState();showFlashcard();$('flashcardForm').classList.add('hidden');$('fcFrontInput').value='';$('fcBackInput').value='';toast('Criado!');}
function showFlashcard(){if(!state.flashcards.length){$('flashcardDisplay').classList.add('hidden');$('flashcardEmpty').classList.remove('hidden');$('flashcardControls').classList.add('hidden');return;}var fc=state.flashcards[state.currentFC%state.flashcards.length];$('fcFront').textContent=fc.front;$('fcBack').textContent=fc.back;$('flashcardDisplay').classList.remove('hidden','flipped');$('flashcardEmpty').classList.add('hidden');$('flashcardControls').classList.remove('hidden');}
function nextFlashcard(){if(!state.flashcards.length)return;state.currentFC=(state.currentFC+1)%state.flashcards.length;showFlashcard();}
function showEventForm(){$('eventForm').classList.remove('hidden');}
function saveEvent(){var title=$('evTitle').value.trim(),date=$('evDate').value;if(!title||!date){toast('Titulo e data obrigatorios');return;}var typ=$('evType').value;state.events.push({id:Date.now(),title:title,date:date,type:typ});state.events.sort(function(a,b){return a.date.localeCompare(b.date);});saveState();renderSchedule();$('eventForm').classList.add('hidden');$('evTitle').value='';toast('Evento salvo!');if(state.googleToken)createGoogleEvent(title,date);}
function renderSchedule(){var list=$('scheduleList');var all=(state.events||[]).concat(state.googleEvents||[]);all.sort(function(a,b){return (a.date||'').localeCompare(b.date||'');});if(!all.length){list.innerHTML='<p class="text-cyan-700 text-sm text-center py-3">Nenhum evento — conecte o Google ou adicione local</p>';return;}list.innerHTML=all.slice(0,20).map(function(e){var badge=e.type==='google'?'Google':e.type;return '<div class="flex justify-between p-2 rounded-lg border border-cyan-900/30" style="background:rgba(10,10,25,.4)"><span class="text-sm text-cyan-200">'+e.title+' <span class="text-[10px] text-cyan-600">('+badge+')</span></span><span class="text-[10px] text-cyan-500">'+e.date+'</span></div>';}).join('');}
function addTask(){var t=prompt('Nova tarefa:');if(!t||!t.trim())return;state.tasks.push({id:Date.now(),title:t.trim(),done:false});saveState();renderTasks();}
function toggleTask(id){var t=state.tasks.find(function(x){return x.id===id;});if(t){t.done=!t.done;saveState();renderTasks();}}
function renderTasks(){var list=$('taskList');if(!state.tasks.length){list.innerHTML='<p class="text-cyan-700 text-sm text-center py-3">Nenhuma tarefa</p>';return;}list.innerHTML=state.tasks.map(function(t){return '<div class="flex items-center gap-2 p-2 rounded-lg border border-cyan-900/30" style="background:rgba(10,10,25,.4)"><input type="checkbox" '+(t.done?'checked':'')+' data-task="'+t.id+'" class="task-check accent-cyan-400"><span class="text-sm '+(t.done?'line-through text-cyan-700':'text-cyan-200')+'">'+t.title+'</span></div>';}).join('');list.querySelectorAll('.task-check').forEach(function(el){el.addEventListener('change',function(){toggleTask(Number(el.getAttribute('data-task')));});});}
function startPomodoro(){if(state.pomodoro.running)return;state.pomodoro.running=true;$('btnPomoStart').textContent='Rodando...';state.pomodoro.interval=setInterval(function(){state.pomodoro.seconds--;updatePomodoroUI();if(state.pomodoro.seconds<=0){clearInterval(state.pomodoro.interval);state.pomodoro.running=false;$('btnPomoStart').textContent='Iniciar';state.stats.pomodoros++;state.stats.focusMinutes+=25;saveState();mishaSpeak('Pomodoro concluido!');}},1000);}
function pausePomodoro(){if(!state.pomodoro.running)return;clearInterval(state.pomodoro.interval);state.pomodoro.running=false;$('btnPomoStart').textContent='Continuar';}
function resetPomodoro(){clearInterval(state.pomodoro.interval);state.pomodoro.running=false;state.pomodoro.seconds=state.pomodoro.total;$('btnPomoStart').textContent='Iniciar';updatePomodoroUI();}
function updatePomodoroUI(){var m=Math.floor(state.pomodoro.seconds/60),s=state.pomodoro.seconds%60;$('pomodoroTime').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');$('pomodoroRing').style.strokeDashoffset=283*(1-state.pomodoro.seconds/state.pomodoro.total);}
function updateHealthUI(){if(!state.profile)return;var w=state.profile.weight,h=state.profile.height;$('healthWeight').textContent=w?w+' kg':'— kg';$('healthHeight').textContent=h?h+' cm':'— cm';if(w&&h)$('healthBMI').textContent=(w/Math.pow(h/100,2)).toFixed(1);if(state.profile.routine)$('healthRoutine').value=state.profile.routine;if(w)$('inputWeight').value=w;if(h)$('inputHeight').value=h;}
function saveHealth(){if(!state.profile)state.profile={name:'Estudante'};var w=parseFloat($('inputWeight').value),h=parseFloat($('inputHeight').value);if(w)state.profile.weight=w;if(h)state.profile.height=h;state.profile.routine=$('healthRoutine').value;saveState();updateHealthUI();toast('Salvo!');}
function loadLocalPdf(e){var f=e.target.files[0];if(!f)return;$('pdfViewer').innerHTML='<iframe src="'+URL.createObjectURL(f)+'" class="w-full h-96 rounded-lg"></iframe>';}
async function generateSummary(){var t=$('summaryInput').value.trim();if(!t){toast('Cole um texto');return;}setOrbState('thinking');var r=await askAI('Resuma em portugues:\n'+t);var el=$('aiOutput');el.textContent=r||'Falha';el.style.display='block';setOrbState('');if(r)mishaSpeak('Resumo pronto.');}
async function generateQuiz(){var t=$('summaryInput').value.trim();if(!t){toast('Cole um texto');return;}setOrbState('thinking');var r=await askAI('Crie quiz de 5 perguntas com gabarito:\n'+t);var el=$('aiOutput');el.textContent=r||'Falha';el.style.display='block';setOrbState('');}
var onboardSteps=[{key:'name',q:'Como posso te chamar?',ph:'Seu nome'},{key:'occupation',q:'O que voce estuda?',ph:'Ex: ENEM'},{key:'goal',q:'Qual sua meta?',ph:'Ex: Passar'}];var onboardIdx=0,onboardData={};
function startOnboarding(){onboardIdx=0;onboardData={};$('onboardingModal').style.display='flex';renderOnboardStep();}
function renderOnboardStep(){var s=onboardSteps[onboardIdx];$('onboardingStep').innerHTML='<p class="text-sm text-cyan-300 mb-3">'+s.q+'</p><input id="onboardInput" class="w-full px-4 py-3 rounded-lg text-sm" placeholder="'+s.ph+'">';$('onboardInput').focus();}
function finishOnboarding(){state.profile={name:onboardData.name||'Estudante',occupation:onboardData.occupation||'',goal:onboardData.goal||''};saveState();$('onboardingModal').style.display='none';updateGreeting();mishaSpeak('Prazer, '+state.profile.name+'!');}
function updateGreeting(){$('userGreeting').textContent='Ola, '+((state.profile&&state.profile.name)||'Estudante');}
var canvas=$('visualizer'),ctx=canvas.getContext('2d'),ang=0;
function draw(){var w=canvas.width,h=canvas.height,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);var sc=$('orb').className;var active=/listening|thinking|speaking/.test(sc);var color=sc.indexOf('thinking')>=0?'168,85,247':sc.indexOf('speaking')>=0?'34,211,238':'0,240,255';var inten=active?1:0.3;for(var i=0;i<3;i++){var r=35+i*16+Math.sin(ang+i)*5*inten;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='rgba('+color+','+(0.15+inten*0.2)+')';ctx.lineWidth=1.5;ctx.stroke();}ang+=0.03*(active?2:1);requestAnimationFrame(draw);}
function switchTab(name){document.querySelectorAll('.tab-btn').forEach(function(b){b.classList.remove('active');b.classList.add('text-cyan-400/70');});document.querySelectorAll('.tab-content').forEach(function(t){t.classList.add('hidden');});var btn=document.querySelector('.tab-btn[data-tab="'+name+'"]');if(btn){btn.classList.add('active');btn.classList.remove('text-cyan-400/70');}var panel=$('tab-'+name);if(panel)panel.classList.remove('hidden');}
function init(){loadState();updateGreeting();updateStatsUI();updateHealthUI();renderSchedule();renderTasks();updatePomodoroUI();updateClock();setInterval(updateClock,30000);draw();
$('btnOpenSettings').addEventListener('click',openSettings);
$('btnCloseSettings').addEventListener('click',closeSettings);
$('btnSaveSettings').addEventListener('click',saveSettings);
var btnG=$('btnConnectGoogle');if(btnG)btnG.addEventListener('click',connectGoogle);
var btnS=$('btnSyncGoogle');if(btnS)btnS.addEventListener('click',function(){if(state.googleToken)loadGoogleCalendar();else connectGoogle();});
$('settingsModal').addEventListener('click',function(e){if(e.target===$('settingsModal'))closeSettings();});
$('btnVoiceMode').addEventListener('click',toggleMic);
$('btnTestVoice').addEventListener('click',function(){mishaSpeak('Oi! Eu sou o Misha.');});
$('btnSendText').addEventListener('click',sendTextCmd);
$('textCmd').addEventListener('keydown',function(e){if(e.key==='Enter')sendTextCmd();});
$('btnClearChat').addEventListener('click',function(){$('chatLog').innerHTML='';state.chatHistory=[];});
document.querySelectorAll('.tab-btn').forEach(function(btn){btn.addEventListener('click',function(){switchTab(btn.getAttribute('data-tab'));});});
$('btnNewFC').addEventListener('click',showFlashcardForm);
$('btnSaveFC').addEventListener('click',saveFlashcard);
$('btnFCNext').addEventListener('click',nextFlashcard);
$('flashcardDisplay').addEventListener('click',function(){this.classList.toggle('flipped');});
$('btnNewEvent').addEventListener('click',showEventForm);
$('btnSaveEvent').addEventListener('click',saveEvent);
$('btnAddTask').addEventListener('click',addTask);
$('btnPomoStart').addEventListener('click',startPomodoro);
$('btnPomoPause').addEventListener('click',pausePomodoro);
$('btnPomoReset').addEventListener('click',resetPomodoro);
$('btnSummary').addEventListener('click',generateSummary);
$('btnQuiz').addEventListener('click',generateQuiz);
$('pdfInput').addEventListener('change',loadLocalPdf);
$('btnSaveHealth').addEventListener('click',saveHealth);
$('onboardNext').addEventListener('click',function(){var v=($('onboardInput')&&$('onboardInput').value.trim())||'';if(!v&&onboardIdx===0){toast('Digite seu nome');return;}onboardData[onboardSteps[onboardIdx].key]=v;onboardIdx++;if(onboardIdx>=onboardSteps.length)finishOnboarding();else renderOnboardStep();});
$('onboardSkip').addEventListener('click',function(){$('onboardingModal').style.display='none';if(!state.profile){state.profile={name:'Estudante'};saveState();}updateGreeting();});
if(state.flashcards.length)showFlashcard();
if(!state.profile)setTimeout(startOnboarding,400);
else if(state.settings.groq||state.settings.gemini)setTimeout(function(){mishaSpeak('Bem-vindo de volta!');},500);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();