(function(){
var STORAGE_KEY='misha_data_v4';
var state={settings:{groq:'',elevenLabs:'',gemini:'',googleClientId:'',voiceURI:'',dailyGoal:120},googleToken:null,googleEvents:[],profile:null,subjects:[],flashcards:[],events:[],tasks:[],notes:[],sessions:[],stats:{pomodoros:0,focusMinutes:0,streak:0,lastStudyDate:null,weekFocus:{}},chatHistory:[],reviewQueue:[],currentFC:0,reviewMode:false,pomodoro:{running:false,seconds:1500,total:1500,interval:null,mode:'foco'},micActive:false,recognition:null,isSpeaking:false};
var SYSTEM_PROMPT='Voce e o MISHA, tutor de estudos baseado em ciencia cognitiva. Fale em portugues do Brasil, natural e curto (2-5 frases). Use active recall, spaced repetition e Feynman quando ajudar. Sem markdown longo. Pode perguntar de volta.';
var SCIENCE_TIPS=['Active recall + spaced repetition tem a maior evidencia (Dunlosky 2013). Testar a si mesmo vale mais que reler.','Interleaving: misture materias na mesma sessao. Melhora discriminacao de problemas (Rohrer 2015).','O esforco desejavel da dificuldade na hora de lembrar fortalece a memoria a longo prazo.','Pomodoro 25/5 reduz fadiga e protege o foco profundo. Depois de 4 ciclos, pause 15-20 min.','Notas Cornell: cues a esquerda, notas a direita, resumo embaixo. Ideal para revisao ativa.','Explicar como se fosse para uma crianca (Feynman) revela exatamente onde voce nao entendeu.','Espacamento: revisar amanha, em 3 dias, 1 semana e 2 semanas multiplica a retencao vs cramming.'];
var tokenClient=null;
function $(id){return document.getElementById(id);}
function todayStr(){return new Date().toISOString().slice(0,10);}
function daysBetween(a,b){return Math.round((new Date(b)-new Date(a))/86400000);}
function loadState(){try{var raw=localStorage.getItem(STORAGE_KEY);if(raw){var s=JSON.parse(raw);if(s.settings)Object.assign(state.settings,s.settings);if(s.profile)state.profile=s.profile;if(s.subjects)state.subjects=s.subjects;if(s.flashcards)state.flashcards=s.flashcards;if(s.events)state.events=s.events;if(s.tasks)state.tasks=s.tasks;if(s.notes)state.notes=s.notes;if(s.sessions)state.sessions=s.sessions;if(s.stats)Object.assign(state.stats,s.stats);}['misha_data_v3','misha_data_v2','misha_data_v1'].forEach(function(k){var old=localStorage.getItem(k);if(!old)return;try{var o=JSON.parse(old);if(o.settings){if(!state.settings.groq&&o.settings.groq)state.settings.groq=o.settings.groq;if(!state.settings.gemini&&o.settings.gemini)state.settings.gemini=o.settings.gemini;if(!state.settings.elevenLabs&&o.settings.elevenLabs)state.settings.elevenLabs=o.settings.elevenLabs;if(!state.settings.googleClientId&&o.settings.googleClientId)state.settings.googleClientId=o.settings.googleClientId;}if(!state.profile&&o.profile)state.profile=o.profile;if(!state.flashcards.length&&o.flashcards){state.flashcards=o.flashcards.map(function(c){return {id:c.id||Date.now()+Math.random(),front:c.front,back:c.back,subject:c.subject||'',ease:2.5,interval:0,reps:0,due:todayStr()};});}if(!state.events.length&&o.events)state.events=o.events;if(!state.tasks.length&&o.tasks)state.tasks=o.tasks;}catch(e){}});}catch(e){}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({settings:state.settings,profile:state.profile,subjects:state.subjects,flashcards:state.flashcards,events:state.events,tasks:state.tasks,notes:state.notes,sessions:state.sessions,stats:state.stats}));updateStatsUI();}
function toast(msg,d){d=d||3000;var el=$('toast');el.textContent=msg;el.style.display='block';setTimeout(function(){el.style.display='none';},d);}
function addChat(role,text){var log=$('chatLog');var div=document.createElement('div');div.className='chat-msg'+(role==='user'?' text-right':'');div.innerHTML='<span class="'+(role==='user'?'text-cyan-300':'text-purple-300')+' font-semibold">'+(role==='user'?'Voce':'MISHA')+':</span> <span class="text-cyan-200">'+text+'</span>';log.appendChild(div);log.scrollTop=log.scrollHeight;}
function setOrbState(s){var orb=$('orb');orb.classList.remove('listening','thinking','speaking');if(s)orb.classList.add(s);$('orbStatus').textContent=({listening:'Ouvindo...',thinking:'Pensando...',speaking:'Falando...','':'Aguardando'})[s]||'Aguardando';}
function getDueCards(){var t=todayStr();return state.flashcards.filter(function(c){return !c.due||c.due<=t;});}
function scheduleCard(card,grade){if(grade===0){card.reps=0;card.interval=0;card.due=todayStr();}else{if(card.reps===0){card.interval=1;}else if(card.reps===1){card.interval=3;}else{var mult=card.ease||2.5;if(grade===1)mult*=0.85;if(grade===3)mult*=1.15;card.interval=Math.max(1,Math.round((card.interval||1)*mult));}card.reps=(card.reps||0)+1;var e=card.ease||2.5;if(grade===1)e-=0.15;else if(grade===3)e+=0.1;else e+=0.05;card.ease=Math.max(1.3,Math.min(3.0,e));var d=new Date();d.setDate(d.getDate()+card.interval);card.due=d.toISOString().slice(0,10);}saveState();}
function updateStatsUI(){$('statPomodoros').textContent=state.stats.pomodoros||0;$('statFlashcards').textContent=state.flashcards.length;var due=getDueCards().length;$('statDue').textContent=due;$('statStreak').textContent=(state.stats.streak||0)+'d';var goal=state.settings.dailyGoal||120;var today=todayStr();var todayMin=(state.stats.weekFocus&&state.stats.weekFocus[today])||0;$('goalText').textContent=todayMin+' / '+goal+' min';$('goalBar').style.width=Math.min(100,Math.round(todayMin/goal*100))+'%';$('dueSummary').textContent=due+' card'+(due===1?'':'s')+' vencido'+(due===1?'':'s');renderWeekStats();renderExamBox();}
function renderWeekStats(){var el=$('weekStats');if(!el)return;var days=[];var now=new Date();for(var i=6;i>=0;i--){var d=new Date(now);d.setDate(d.getDate()-i);days.push(d.toISOString().slice(0,10));}var labels=['D','S','T','Q','Q','S','S'];el.innerHTML=days.map(function(ds,i){var m=(state.stats.weekFocus&&state.stats.weekFocus[ds])||0;var h=Math.min(40,8+m/3);return '<div><div class="mx-auto mb-1 rounded" style="width:100%;max-width:28px;height:'+h+'px;background:linear-gradient(180deg,rgba(0,240,255,.5),rgba(168,85,247,.4))"></div><span class="text-cyan-600">'+labels[new Date(ds+'T12:00:00').getDay()]+'</span><br><span class="text-cyan-500">'+m+'m</span></div>';}).join('');}
function renderExamBox(){var provas=state.events.filter(function(e){return e.type==='prova'&&e.date>=todayStr();}).sort(function(a,b){return a.date.localeCompare(b.date);});var box=$('examBox');if(!provas.length){box.textContent='Nenhuma prova cadastrada';return;}var p=provas[0];var days=daysBetween(todayStr(),p.date);box.innerHTML='<p class="font-semibold text-cyan-100">'+p.title+'</p><p class="text-xs text-purple-300 mt-1">'+p.date+' · '+(days===0?'HOJE':days+' dia'+(days===1?'':'s'))+'</p>';}
function openSettings(){$('cfgGroq').value=state.settings.groq||'';$('cfgEleven').value=state.settings.elevenLabs||'';$('cfgGemini').value=state.settings.gemini||'';var gc=$('cfgGoogleClient');if(gc)gc.value=state.settings.googleClientId||'';var dg=$('cfgDailyGoal');if(dg)dg.value=state.settings.dailyGoal||120;populateVoices();$('settingsModal').style.display='flex';}
function closeSettings(){$('settingsModal').style.display='none';}
function saveSettings(){state.settings.groq=$('cfgGroq').value.trim();state.settings.elevenLabs=$('cfgEleven').value.trim();state.settings.gemini=$('cfgGemini').value.trim();var gc=$('cfgGoogleClient');if(gc)state.settings.googleClientId=gc.value.trim();state.settings.voiceURI=$('cfgVoice').value;var dg=$('cfgDailyGoal');if(dg)state.settings.dailyGoal=parseInt(dg.value,10)||120;saveState();closeSettings();toast('Salvo!');if(!state.settings.groq&&!state.settings.gemini)toast('Sem chave Groq a IA nao conversa de verdade',4000);}
function populateVoices(){var sel=$('cfgVoice');sel.innerHTML='';speechSynthesis.getVoices().forEach(function(v){var o=document.createElement('option');o.value=v.voiceURI;o.textContent=v.name+' ('+v.lang+')';if(v.voiceURI===state.settings.voiceURI)o.selected=true;sel.appendChild(o);});}
speechSynthesis.onvoiceschanged=populateVoices;
function stopSpeaking(){try{speechSynthesis.cancel();}catch(e){}state.isSpeaking=false;}
function resumeMic(){if(state.micActive&&state.recognition)setTimeout(function(){try{state.recognition.start();}catch(e){}},400);}
function fallbackSpeak(text){stopSpeaking();state.isSpeaking=true;setOrbState('speaking');var u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=1.02;var voices=speechSynthesis.getVoices();var p=null;for(var i=0;i<voices.length;i++){if(voices[i].voiceURI===state.settings.voiceURI){p=voices[i];break;}}if(!p){for(var j=0;j<voices.length;j++){if(voices[j].lang.indexOf('pt')===0){p=voices[j];break;}}}if(p)u.voice=p;u.onend=u.onerror=function(){state.isSpeaking=false;setOrbState(state.micActive?'listening':'');resumeMic();};speechSynthesis.speak(u);}
async function mishaSpeak(text){if(!text)return;stopSpeaking();addChat('misha',text);setOrbState('speaking');state.isSpeaking=true;if(state.recognition&&state.micActive)try{state.recognition.stop();}catch(e){}if(state.settings.elevenLabs){try{var res=await fetch('https://api.elevenlabs.io/v1/text-to-speech/pNInz6obpgDQGcFmaJgB',{method:'POST',headers:{'Accept':'audio/mpeg','Content-Type':'application/json','xi-api-key':state.settings.elevenLabs},body:JSON.stringify({text:text,model_id:'eleven_multilingual_v2',voice_settings:{stability:0.5,similarity_boost:0.75}})});if(res.ok){var url=URL.createObjectURL(await res.blob());var audio=new Audio(url);audio.onended=function(){state.isSpeaking=false;setOrbState(state.micActive?'listening':'');URL.revokeObjectURL(url);resumeMic();};audio.onerror=function(){fallbackSpeak(text);};await audio.play();return;}}catch(e){}}fallbackSpeak(text);}
function initRecognition(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Use o Chrome para voz');return null;}var rec=new SR();rec.continuous=true;rec.interimResults=true;rec.lang='pt-BR';rec.onresult=function(e){if(state.isSpeaking)return;var interim='',finalText='';for(var i=e.resultIndex;i<e.results.length;i++){var t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=t;else interim+=t;}var lh=$('lastHeard');if(finalText)lh.textContent='Ouvi: "'+finalText.trim()+'"';else if(interim)lh.textContent='Ouvindo: "'+interim.trim()+'..."';if(finalText.trim())handleVoiceInput(finalText.trim());};rec.onerror=function(e){if(e.error==='not-allowed'){toast('Mic bloqueado');stopMic();}};rec.onend=function(){if(state.micActive&&!state.isSpeaking)try{rec.start();}catch(e){}};return rec;}
function startMic(){if(!state.recognition)state.recognition=initRecognition();if(!state.recognition)return;try{state.recognition.start();state.micActive=true;$('micIcon').textContent='\uD83D\uDD34';$('micBtnText').textContent='PARAR';$('btnVoiceMode').classList.add('active');$('micStatus').className='status-dot online';$('micStatusText').textContent='Ouvindo';setOrbState('listening');toast('Pode falar!');}catch(e){toast('Erro no mic');}}
function stopMic(){state.micActive=false;if(state.recognition)try{state.recognition.stop();}catch(e){}$('micIcon').textContent='\uD83C\uDF99';$('micBtnText').textContent='FALAR COM O MISHA';$('btnVoiceMode').classList.remove('active');$('micStatus').className='status-dot offline';$('micStatusText').textContent='Mic offline';setOrbState('');$('lastHeard').textContent='';}
function toggleMic(){state.micActive?stopMic():startMic();}
function handleVoiceInput(transcript){if(!transcript||state.isSpeaking)return;$('lastHeard').textContent='Ouvi: "'+transcript+'"';var cmd=transcript.replace(/\b(misha|micha|mixa|misa|mecha)\b/gi,'').trim();if(!cmd||cmd.length<2)return;addChat('user',transcript);processCommand(cmd);}
function sendTextCmd(){var input=$('textCmd');var text=(input.value||'').trim();if(!text)return;input.value='';addChat('user',text);processCommand(text);}
function initGoogleAuth(){if(typeof google==='undefined'||!google.accounts){toast('Google ainda carregando');return false;}if(!state.settings.googleClientId){toast('Cole o Google Client ID');return false;}tokenClient=google.accounts.oauth2.initTokenClient({client_id:state.settings.googleClientId,scope:'https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.readonly',callback:function(resp){if(resp&&resp.access_token){state.googleToken=resp.access_token;var gs=$('googleStatus');if(gs)gs.textContent='Conectado';toast('Google conectado!');loadGoogleCalendar();}else toast('Falha Google');}});return true;}
function connectGoogle(){if(!state.settings.googleClientId){openSettings();toast('Cole o Client ID e salve');return;}if(!initGoogleAuth())return;tokenClient.requestAccessToken({prompt:'consent'});}
async function loadGoogleCalendar(){if(!state.googleToken){toast('Conecte o Google primeiro');return;}try{var timeMin=new Date();timeMin.setDate(timeMin.getDate()-7);var timeMax=new Date();timeMax.setDate(timeMax.getDate()+60);var url='https://www.googleapis.com/calendar/v3/calendars/primary/events?maxResults=30&orderBy=startTime&singleEvents=true&timeMin='+encodeURIComponent(timeMin.toISOString())+'&timeMax='+encodeURIComponent(timeMax.toISOString());var res=await fetch(url,{headers:{'Authorization':'Bearer '+state.googleToken}});var data=await res.json();if(data.error){toast('Erro: '+(data.error.message||''));return;}state.googleEvents=(data.items||[]).map(function(ev){var start=(ev.start&&(ev.start.dateTime||ev.start.date))||'';return {id:ev.id,title:ev.summary||'(sem titulo)',date:start.slice(0,10),type:'google'};});renderSchedule();toast(state.googleEvents.length+' eventos Google');}catch(e){toast('Erro Calendar');}}
async function createGoogleEvent(title,date){if(!state.googleToken)return;try{await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{'Authorization':'Bearer '+state.googleToken,'Content-Type':'application/json'},body:JSON.stringify({summary:title,start:{date:date},end:{date:date}})});toast('Criado no Google');loadGoogleCalendar();}catch(e){}}
async function askAI(userMsg,extra){state.chatHistory.push({role:'user',content:userMsg});if(state.chatHistory.length>14)state.chatHistory=state.chatHistory.slice(-14);var sys=SYSTEM_PROMPT+(extra?' '+extra:'');if(state.profile)sys+=' Estudante: '+(state.profile.name||'')+'. Estuda: '+(state.profile.occupation||'')+'. Meta: '+(state.profile.goal||'')+'.';if(state.subjects.length)sys+=' Materias: '+state.subjects.join(', ')+'.';if(state.settings.groq){try{var messages=[{role:'system',content:sys}].concat(state.chatHistory);var models=['openai/gpt-oss-20b','openai/gpt-oss-120b','qwen/qwen3.8-27b','qwen/qwen3.6-27b'];var lastErr='';for(var gi=0;gi<models.length;gi++){var res=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.groq},body:JSON.stringify({model:models[gi],messages:messages,temperature:0.85,max_tokens:500})});var data=await res.json();if(data&&data.error){lastErr=data.error.message||'';continue;}if(data&&data.choices&&data.choices[0]&&data.choices[0].message){var reply=(data.choices[0].message.content||'').trim();if(reply){state.chatHistory.push({role:'assistant',content:reply});return reply;}}}if(lastErr)toast('Erro Groq: '+lastErr,4000);}catch(e){console.warn(e);}}if(state.settings.gemini){try{var gModels=['gemini-2.5-flash','gemini-2.5-flash-lite','gemini-flash-latest'];var hist=state.chatHistory.slice(-6).map(function(m){return(m.role==='user'?'Usuario: ':'MISHA: ')+m.content;}).join('\n');var prompt=sys+'\n\n'+hist+'\n\nResponda em tom de conversa.';for(var mi=0;mi<gModels.length;mi++){var gRes=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+gModels[mi]+':generateContent?key='+encodeURIComponent(state.settings.gemini),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.85,maxOutputTokens:500}})});var gData=await gRes.json();if(gData&&gData.error)continue;var gReply=gData&&gData.candidates&&gData.candidates[0]&&gData.candidates[0].content&&gData.candidates[0].content.parts&&gData.candidates[0].content.parts[0]&&gData.candidates[0].content.parts[0].text;if(gReply){gReply=gReply.trim();state.chatHistory.push({role:'assistant',content:gReply});return gReply;}}}catch(e){}}return null;}
async function processCommand(cmd){setOrbState('thinking');var lower=cmd.toLowerCase();if(/pomodoro|timer|foco/.test(lower)){if(/parar|pausar/.test(lower)){pausePomodoro();mishaSpeak('Pomodoro pausado.');return;}startPomodoro();mishaSpeak('Pomodoro iniciado. Foque agora.');return;}if(/revis(ar|ao)|flashcard|card/.test(lower)){var due=getDueCards();if(due.length){startReview();mishaSpeak('Tem '+due.length+' cards para revisar. Aba Cards.');}else mishaSpeak('Nenhum card vencido hoje. Bom trabalho!');return;}if(/que horas|horario/.test(lower)){mishaSpeak('Agora sao '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+'.');return;}var reply=await askAI(cmd);if(reply)mishaSpeak(reply);else mishaSpeak('Coloca a chave Groq em Configuracoes. console.groq.com/keys');}
function renderSubjects(){var el=$('subjectList');if(!state.subjects.length){el.innerHTML='<span class="text-cyan-700 text-xs">Nenhuma materia ainda</span>';return;}el.innerHTML=state.subjects.map(function(s){return '<span class="text-xs px-2 py-1 rounded-full border border-cyan-700 text-cyan-300">'+s+'</span>';}).join('');fillSubjectSelects();}
function fillSubjectSelects(){['fcSubject','fcSubjectFilter','noteSubject','evSubject'].forEach(function(id){var sel=$(id);if(!sel)return;var cur=sel.value;var isFilter=id==='fcSubjectFilter';sel.innerHTML=isFilter?'<option value="">Todas</option>':'<option value="">Geral</option>';state.subjects.forEach(function(s){var o=document.createElement('option');o.value=s;o.textContent=s;sel.appendChild(o);});sel.value=cur;});}
function addSubject(){var n=prompt('Nome da materia:');if(!n||!n.trim())return;n=n.trim();if(state.subjects.indexOf(n)<0){state.subjects.push(n);saveState();renderSubjects();toast('Materia adicionada');}}
function showFlashcardForm(){$('flashcardForm').classList.remove('hidden');}
function saveFlashcard(){var f=$('fcFrontInput').value.trim(),b=$('fcBackInput').value.trim();if(!f||!b){toast('Preencha frente e verso');return;}state.flashcards.push({id:Date.now(),front:f,back:b,subject:$('fcSubject').value||'',ease:2.5,interval:0,reps:0,due:todayStr()});saveState();$('flashcardForm').classList.add('hidden');$('fcFrontInput').value='';$('fcBackInput').value='';toast('Card criado!');showFlashcard();}
function getFilteredCards(){var filter=$('fcSubjectFilter')?$('fcSubjectFilter').value:'';if(state.reviewMode)return state.reviewQueue;var list=state.flashcards;if(filter)list=list.filter(function(c){return c.subject===filter;});return list;}
function showFlashcard(){var list=getFilteredCards();if(!list.length){$('flashcardDisplay').classList.add('hidden');$('flashcardEmpty').classList.remove('hidden');$('flashcardControls').classList.add('hidden');return;}if(state.currentFC>=list.length)state.currentFC=0;var fc=list[state.currentFC];$('fcFront').textContent=fc.front;$('fcBack').textContent=fc.back;$('flashcardDisplay').classList.remove('hidden','flipped');$('flashcardEmpty').classList.add('hidden');$('flashcardControls').classList.remove('hidden');$('fcMeta').textContent=(fc.subject?fc.subject+' · ':'')+'reps '+(fc.reps||0)+' · intervalo '+(fc.interval||0)+'d · due '+(fc.due||'?');}
function rateCard(grade){var list=getFilteredCards();if(!list.length)return;var fc=list[state.currentFC];var master=state.flashcards.find(function(c){return c.id===fc.id;});if(master)scheduleCard(master,grade);if(state.reviewMode){state.reviewQueue.splice(state.currentFC,1);if(!state.reviewQueue.length){state.reviewMode=false;toast('Revisao concluida!');mishaSpeak('Revisao concluida. Excelente!');}showFlashcard();}else{state.currentFC=(state.currentFC+1)%Math.max(1,getFilteredCards().length);showFlashcard();}updateStatsUI();}
function startReview(){state.reviewQueue=getDueCards().slice();if(!state.reviewQueue.length){toast('Nada para revisar hoje');return;}state.reviewMode=true;state.currentFC=0;switchTab('cards');showFlashcard();toast(state.reviewQueue.length+' cards na fila');}
function showNoteForm(){$('noteForm').classList.remove('hidden');}
function saveNote(){var title=$('noteTitle').value.trim();if(!title){toast('Titulo obrigatorio');return;}state.notes.unshift({id:Date.now(),title:title,cues:$('noteCues').value,body:$('noteBody').value,summary:$('noteSummary').value,subject:$('noteSubject').value||'',date:todayStr()});saveState();$('noteForm').classList.add('hidden');$('noteTitle').value='';$('noteCues').value='';$('noteBody').value='';$('noteSummary').value='';renderNotes();toast('Nota salva!');}
function renderNotes(){var el=$('notesList');if(!state.notes.length){el.innerHTML='<p class="text-cyan-700 text-xs">Nenhuma nota</p>';return;}el.innerHTML=state.notes.slice(0,30).map(function(n){return '<div class="p-3 rounded-lg border border-cyan-900/30" style="background:rgba(10,10,25,.4)"><div class="flex justify-between"><span class="text-sm text-cyan-200 font-semibold">'+n.title+'</span><span class="text-[10px] text-cyan-600">'+n.date+(n.subject?' · '+n.subject:'')+'</span></div>'+(n.summary?'<p class="text-[11px] text-cyan-400 mt-1">'+n.summary.slice(0,120)+'</p>':'')+'</div>';}).join('');}
function showEventForm(){$('eventForm').classList.remove('hidden');}
function saveEvent(){var title=$('evTitle').value.trim(),date=$('evDate').value;if(!title||!date){toast('Titulo e data obrigatorios');return;}var typ=$('evType').value;state.events.push({id:Date.now(),title:title,date:date,type:typ,subject:$('evSubject').value||''});state.events.sort(function(a,b){return a.date.localeCompare(b.date);});saveState();renderSchedule();renderExamBox();$('eventForm').classList.add('hidden');$('evTitle').value='';toast('Evento salvo!');if(state.googleToken)createGoogleEvent(title,date);}
function renderSchedule(){var list=$('scheduleList');var all=(state.events||[]).concat(state.googleEvents||[]);all.sort(function(a,b){return (a.date||'').localeCompare(b.date||'');});if(!all.length){list.innerHTML='<p class="text-cyan-700 text-sm text-center py-3">Nenhum evento</p>';return;}list.innerHTML=all.slice(0,25).map(function(e){var badge=e.type==='google'?'Google':e.type;return '<div class="flex justify-between p-2 rounded-lg border border-cyan-900/30" style="background:rgba(10,10,25,.4)"><span class="text-sm text-cyan-200">'+e.title+' <span class="text-[10px] text-cyan-600">('+badge+')</span></span><span class="text-[10px] text-cyan-500">'+e.date+'</span></div>';}).join('');}
function addTask(){var t=prompt('Nova tarefa:');if(!t||!t.trim())return;state.tasks.push({id:Date.now(),title:t.trim(),done:false});saveState();renderTasks();}
function toggleTask(id){var t=state.tasks.find(function(x){return x.id===id;});if(t){t.done=!t.done;saveState();renderTasks();}}
function renderTasks(){var list=$('taskList');if(!state.tasks.length){list.innerHTML='<p class="text-cyan-700 text-sm text-center py-3">Nenhuma tarefa</p>';return;}list.innerHTML=state.tasks.map(function(t){return '<div class="flex items-center gap-2 p-2 rounded-lg border border-cyan-900/30" style="background:rgba(10,10,25,.4)"><input type="checkbox" '+(t.done?'checked':'')+' data-task="'+t.id+'" class="task-check accent-cyan-400"><span class="text-sm '+(t.done?'line-through text-cyan-700':'text-cyan-200')+'">'+t.title+'</span></div>';}).join('');list.querySelectorAll('.task-check').forEach(function(el){el.addEventListener('change',function(){toggleTask(Number(el.getAttribute('data-task')));});});}
function setPomoMinutes(m){if(state.pomodoro.running)return;state.pomodoro.total=m*60;state.pomodoro.seconds=m*60;state.pomodoro.mode=m<=5?'pausa':'foco';$('pomodoroMode').textContent=state.pomodoro.mode==='pausa'?'Pausa':'Foco';updatePomodoroUI();}
function startPomodoro(){if(state.pomodoro.running)return;state.pomodoro.running=true;$('btnPomoStart').textContent='Rodando...';state.pomodoro.interval=setInterval(function(){state.pomodoro.seconds--;updatePomodoroUI();if(state.pomodoro.seconds<=0){clearInterval(state.pomodoro.interval);state.pomodoro.running=false;$('btnPomoStart').textContent='Iniciar';if(state.pomodoro.mode!=='pausa'){var mins=Math.round(state.pomodoro.total/60);state.stats.pomodoros=(state.stats.pomodoros||0)+1;state.stats.focusMinutes=(state.stats.focusMinutes||0)+mins;var t=todayStr();if(!state.stats.weekFocus)state.stats.weekFocus={};state.stats.weekFocus[t]=(state.stats.weekFocus[t]||0)+mins;var last=state.stats.lastStudyDate;if(last===t){}else if(last&&daysBetween(last,t)===1)state.stats.streak=(state.stats.streak||0)+1;else state.stats.streak=1;state.stats.lastStudyDate=t;state.sessions.unshift({date:t,minutes:mins,type:'pomodoro'});if(state.sessions.length>60)state.sessions=state.sessions.slice(0,60);saveState();renderSessionLog();mishaSpeak('Pomodoro concluido! '+mins+' minutos de foco. Hora de uma pausa curta.');}else mishaSpeak('Pausa acabou. Bora voltar?');}},1000);}
function pausePomodoro(){if(!state.pomodoro.running)return;clearInterval(state.pomodoro.interval);state.pomodoro.running=false;$('btnPomoStart').textContent='Continuar';}
function resetPomodoro(){clearInterval(state.pomodoro.interval);state.pomodoro.running=false;state.pomodoro.seconds=state.pomodoro.total;$('btnPomoStart').textContent='Iniciar';updatePomodoroUI();}
function updatePomodoroUI(){var m=Math.floor(state.pomodoro.seconds/60),s=state.pomodoro.seconds%60;$('pomodoroTime').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');$('pomodoroRing').style.strokeDashoffset=283*(1-state.pomodoro.seconds/state.pomodoro.total);}
function renderSessionLog(){var el=$('sessionLog');if(!el)return;if(!state.sessions.length){el.innerHTML='<p class="text-cyan-700">Nenhuma sessao ainda</p>';return;}el.innerHTML=state.sessions.slice(0,15).map(function(s){return '<div class="flex justify-between"><span>'+s.date+'</span><span>'+s.minutes+' min</span></div>';}).join('');}
async function runAIMode(mode){var topic=$('aiTopic').value.trim();if(!topic&&mode!=='plan'){toast('Cole um topico ou texto');return;}setOrbState('thinking');var prompts={explain:'Explique de forma simples, como se eu tivesse 12 anos (tecnica Feynman). Depois faca 2 perguntas para eu testar se entendi:\n'+topic,quiz:'Faca 5 perguntas de active recall sobre o conteudo abaixo. Nao de o gabarito ainda; peca que eu responda:\n'+topic,gaps:'Quais sao os pontos que um estudante costuma errar ou deixar vago neste assunto? Liste e explique cada um:\n'+topic,plan:'Crie um plano de estudo intercalado (interleaving) de 5 dias, com sessoes de 25-50 min, misturando topicos. Contexto: '+topic,summary:'Gere um resumo ativo: 5 perguntas-chave + respostas curtas que eu deveria conseguir lembrar de cabeca:\n'+topic,critique:'Eu vou estudar isto. Me diga o que esta bem e o que falta para dominar o tema:\n'+topic};var r=await askAI(prompts[mode]||topic,'Responda de forma util para estudo, estruturada mas sem markdown excessivo.');var el=$('aiOutput');el.textContent=r||'Falha — confira a chave Groq.';el.style.display='block';setOrbState('');if(r)mishaSpeak('Pronto. Confira o resultado na tela.');}
async function quizFromCards(){var list=state.flashcards.slice(0,8);if(!list.length){toast('Crie cards primeiro');return;}var q=list.map(function(c,i){return (i+1)+') '+c.front;}).join('\n');var el=$('quizBox');el.style.display='block';el.textContent='Responda de cabeca:\n\n'+q+'\n\n(vire os cards depois para conferir)';}
async function quizTopicAI(){var t=prompt('Qual topico?');if(!t)return;setOrbState('thinking');var r=await askAI('Crie 5 perguntas de active recall sobre: '+t+'. Sem gabarito ainda.');var el=$('quizBox');el.style.display='block';el.textContent=r||'Falha';setOrbState('');}
function updateHealthUI(){if(!state.profile)return;var w=state.profile.weight,h=state.profile.height;$('healthWeight').textContent=w?w+' kg':'— kg';$('healthHeight').textContent=h?h+' cm':'— cm';if(w&&h)$('healthBMI').textContent=(w/Math.pow(h/100,2)).toFixed(1);if(state.profile.routine)$('healthRoutine').value=state.profile.routine;if(w)$('inputWeight').value=w;if(h)$('inputHeight').value=h;}
function saveHealth(){if(!state.profile)state.profile={name:'Estudante'};var w=parseFloat($('inputWeight').value),h=parseFloat($('inputHeight').value);if(w)state.profile.weight=w;if(h)state.profile.height=h;state.profile.routine=$('healthRoutine').value;saveState();updateHealthUI();toast('Salvo!');}
function loadLocalPdf(e){var f=e.target.files[0];if(!f)return;$('pdfViewer').innerHTML='<iframe src="'+URL.createObjectURL(f)+'" class="w-full h-64 rounded-lg"></iframe>';}
var onboardSteps=[{key:'name',q:'Como posso te chamar?',ph:'Seu nome'},{key:'occupation',q:'O que voce estuda?',ph:'Ex: ENEM, Medicina, Direito'},{key:'goal',q:'Qual sua meta principal?',ph:'Ex: Passar em Medicina'}];var onboardIdx=0,onboardData={};
function startOnboarding(){onboardIdx=0;onboardData={};$('onboardingModal').style.display='flex';renderOnboardStep();}
function renderOnboardStep(){var s=onboardSteps[onboardIdx];$('onboardingStep').innerHTML='<p class="text-sm text-cyan-300 mb-3">'+s.q+'</p><input id="onboardInput" class="w-full px-4 py-3 rounded-lg text-sm" placeholder="'+s.ph+'">';$('onboardInput').focus();}
function finishOnboarding(){state.profile={name:onboardData.name||'Estudante',occupation:onboardData.occupation||'',goal:onboardData.goal||''};saveState();$('onboardingModal').style.display='none';updateGreeting();mishaSpeak('Prazer, '+state.profile.name+'! Configure o Groq e vamos estudar de verdade.');if(!state.settings.groq)setTimeout(openSettings,800);}
function updateGreeting(){$('userGreeting').textContent='Ola, '+((state.profile&&state.profile.name)||'Estudante');}
var canvas=$('visualizer'),ctx=canvas.getContext('2d'),ang=0;
function draw(){var w=canvas.width,h=canvas.height,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);var sc=$('orb').className;var active=/listening|thinking|speaking/.test(sc);var color=sc.indexOf('thinking')>=0?'168,85,247':sc.indexOf('speaking')>=0?'34,211,238':'0,240,255';var inten=active?1:0.3;for(var i=0;i<3;i++){var r=30+i*14+Math.sin(ang+i)*4*inten;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='rgba('+color+','+(0.15+inten*0.2)+')';ctx.lineWidth=1.5;ctx.stroke();}ang+=0.03*(active?2:1);requestAnimationFrame(draw);}
function switchTab(name){document.querySelectorAll('.tab-btn').forEach(function(b){b.classList.remove('active');b.classList.add('text-cyan-400/70');});document.querySelectorAll('.tab-content').forEach(function(t){t.classList.add('hidden');});var btn=document.querySelector('.tab-btn[data-tab="'+name+'"]');if(btn){btn.classList.add('active');btn.classList.remove('text-cyan-400/70');}var panel=$('tab-'+name);if(panel)panel.classList.remove('hidden');}
function init(){loadState();updateGreeting();updateStatsUI();updateHealthUI();renderSchedule();renderTasks();renderNotes();renderSubjects();renderSessionLog();updatePomodoroUI();updateClock();setInterval(updateClock,30000);$('scienceTip').textContent=SCIENCE_TIPS[Math.floor(Math.random()*SCIENCE_TIPS.length)];draw();
$('btnOpenSettings').addEventListener('click',openSettings);$('btnCloseSettings').addEventListener('click',closeSettings);$('btnSaveSettings').addEventListener('click',saveSettings);
var btnG=$('btnConnectGoogle');if(btnG)btnG.addEventListener('click',connectGoogle);
var btnS=$('btnSyncGoogle');if(btnS)btnS.addEventListener('click',function(){if(state.googleToken)loadGoogleCalendar();else connectGoogle();});
$('settingsModal').addEventListener('click',function(e){if(e.target===$('settingsModal'))closeSettings();});
$('btnVoiceMode').addEventListener('click',toggleMic);$('btnTestVoice').addEventListener('click',function(){mishaSpeak('Oi! Eu sou o Misha, seu tutor de estudos.');});
$('btnSendText').addEventListener('click',sendTextCmd);$('textCmd').addEventListener('keydown',function(e){if(e.key==='Enter')sendTextCmd();});
$('btnClearChat').addEventListener('click',function(){$('chatLog').innerHTML='';state.chatHistory=[];});
document.querySelectorAll('.tab-btn').forEach(function(btn){btn.addEventListener('click',function(){switchTab(btn.getAttribute('data-tab'));});});
$('btnStartReview').addEventListener('click',startReview);$('btnAddSubject').addEventListener('click',addSubject);
$('btnNewFC').addEventListener('click',showFlashcardForm);$('btnSaveFC').addEventListener('click',saveFlashcard);
$('btnFCAgain').addEventListener('click',function(){rateCard(0);});$('btnFCHard').addEventListener('click',function(){rateCard(1);});$('btnFCGood').addEventListener('click',function(){rateCard(2);});$('btnFCEasy').addEventListener('click',function(){rateCard(3);});
$('flashcardDisplay').addEventListener('click',function(){this.classList.toggle('flipped');});
if($('fcSubjectFilter'))$('fcSubjectFilter').addEventListener('change',function(){state.currentFC=0;state.reviewMode=false;showFlashcard();});
$('btnQuizFromCards').addEventListener('click',quizFromCards);$('btnQuizTopic').addEventListener('click',quizTopicAI);
$('btnPomoStart').addEventListener('click',startPomodoro);$('btnPomoPause').addEventListener('click',pausePomodoro);$('btnPomoReset').addEventListener('click',resetPomodoro);
document.querySelectorAll('.pomo-preset').forEach(function(b){b.addEventListener('click',function(){setPomoMinutes(parseInt(b.getAttribute('data-pomo'),10));});});
$('btnAddTask').addEventListener('click',addTask);$('btnNewNote').addEventListener('click',showNoteForm);$('btnSaveNote').addEventListener('click',saveNote);
$('pdfInput').addEventListener('change',loadLocalPdf);$('btnNewEvent').addEventListener('click',showEventForm);$('btnSaveEvent').addEventListener('click',saveEvent);
document.querySelectorAll('.ai-mode').forEach(function(b){b.addEventListener('click',function(){runAIMode(b.getAttribute('data-aimode'));});});
$('btnSaveHealth').addEventListener('click',saveHealth);
$('onboardNext').addEventListener('click',function(){var v=($('onboardInput')&&$('onboardInput').value.trim())||'';if(!v&&onboardIdx===0){toast('Digite seu nome');return;}onboardData[onboardSteps[onboardIdx].key]=v;onboardIdx++;if(onboardIdx>=onboardSteps.length)finishOnboarding();else renderOnboardStep();});
$('onboardSkip').addEventListener('click',function(){$('onboardingModal').style.display='none';if(!state.profile){state.profile={name:'Estudante'};saveState();}updateGreeting();if(!state.settings.groq)setTimeout(openSettings,500);});
if(state.flashcards.length)showFlashcard();
if(!state.profile)setTimeout(startOnboarding,400);
else if(state.settings.groq||state.settings.gemini)setTimeout(function(){mishaSpeak('Bem-vindo de volta! '+getDueCards().length+' cards para revisar.');},600);
else setTimeout(function(){openSettings();toast('Cole a chave Groq para a IA funcionar');},600);}
function updateClock(){$('clockDisplay').textContent=new Date().toLocaleString('pt-BR',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();